### ISSUE TITLE
databases contain absolute paths

### ISSUE THREAD

**Issue by frederic-mahe** [amoore2600/Disk-Packs-Lists-Database#1]
hi @amoore2600 

Nice work with these packs for disk-based consoles!

I noticed that your databases contain absolute paths. This is a use-case I did not anticipate. Absolute paths could create problems when building packs. I've just modified the `parse_pack.py` script to fix that (see https://github.com/SmokeMonsterPacks/EverDrive-Packs-Lists-Database/commit/1a5052147d07c8b62cbb2f8e23dacc980b82db83).

Rather than parsing again all your files, I suggest to fix them in-place:
```sh
for f in *AMDB.txt ; do sed -i 's|\t\/|\t|1' "${f}" ; done
``````
commit with git and push again to github.

**Comment by amoore2600** [comment]
Awesome! I will let you know once this is done.

**Comment by amoore2600** [comment]
I have removed the leading / on all file paths. 

Let me know if you have any questions.
